zeke/semantic-pull-requests

- lib/handle-pull-request-change.js
This PR updates the description text from "ready for review" to  "good to go"
Old description:
> update green status description

- __tests__/handle-pull-request-change.js
- lib/handle-pull-request-change.js
- lib/is-semantic-message.js
- package-lock.json
- package.json
This PR updates the standard linter to [v12](https://standardjs.com/changelog.html#1200---2018-08-28) and fixes any new violations reported by the tool.
> chore(package): update standard to v12

- lib/is-semantic-message.js
- package-lock.json
- package.json
So yea. A lot has changed in v3, it's amazing!
Ii has validate, stringify and parse.
Validate runs `.check` in "loose" if I can call it that way. It checks for valid pattern like `<type>[scope]: <subject>`, so `foo bar baz` will fail. Also, checks if the scope is empty, so `fix(): bar qux` will fail too, but `fix: bar qux` won't. Empty body and empty footer are allowed (and that's what 3.1 and 3.2 are), because we rely behave like `git commit` seems to add empty new line, which can be seen in `git log` - after parsing. 
There is a huge amount of tests there, so it's guaranteed.
We use the `ret` option of `.validate` because we want to check further the commit type against the `conventional-commit-types`.
> fix(is-semantic): update to latest parse-commit-message

- README.md
- __tests__/handle-pull-request-change.js
- lib/handle-pull-request-change.js
- package-lock.json
- package.json
What are your thoughts about having the config file as it seems that the config file will now be required even if the user wants the default settings? I am confirming this here https://github.com/probot/probot-config/issues/23
This is useful when merging by squashing as the PR title is the default
commit message for the squash commit.
Closes #29
-----
[View rendered README.md](https://github.com/guyfedwards/semantic-pull-requests/blob/only-title-linting-option/README.md)
> feat: add config option to only lint PR title

- README.md
- __tests__/handle-pull-request-change.js
- lib/handle-pull-request-change.js
Useful when using Rebase + Merge as merge strategy.
Closes #31
-----
[View rendered README.md](https://github.com/stefanbuck/semantic-pull-requests/blob/feat-commitsOnly/README.md)
> feat: add config option to only lint commits

- lib/handle-pull-request-change.js
In the case that `semantic.yml` does not exist, `getConfig` returns `null`, and the destructuring fails. This adds default options so that `getConfig` will never return `null`.
Prior to #33, we were incorrectly destructuring off the Promise returned from `getConfig` because we weren't `await`ing the Promise.
> fix: add default options to ensure getConfig never returns null

- __tests__/handle-pull-request-change.js
- lib/handle-pull-request-change.js
In my config:
```yaml
titleOnly: true
```
I have a repo configured to only squash commit PRs and because of this, the title should always be valid.
I had a PR with some `semantic commits` but not a `semantic title`.
This PR should be blocked as the commits don't matter to me, only the title.
The status was OK, my PR got blocked.
But, the description was incorrectly showing: `Pending — ready to be merged or rebased`
When it should display: `Pending — add a semantic PR title`
> fix: fixing ready messages when using commitsOnly or titleOnly

- README.md
- __tests__/handle-pull-request-change.js
- lib/handle-pull-request-change.js
- lib/is-semantic-message.js
Github allow users to update branch of a pull request that is not update to date with target branch
If you do so, you have a merge commit in the PR: Merge branch 'master' into feature/ride-unicorns
What if we could allow this kind of commits with a specific option ?
TADA: `allowMergeCommits`: true is here !
This option is disable by default
-----
[View rendered README.md](https://github.com/clakech/semantic-pull-requests/blob/allowMerge/README.md)
> feat: allow merge commit config

- __tests__/handle-pull-request-change.js
- __tests__/is-semantic-message.js
I face issue when testing latest feature allowing Merge Commits on my repos so I create more tests to verify the behaviour of the code. This does not solve my issues but those tests could help avoid regression later
> test: verify isSemanticMessage allow merge commits

- __tests__/handle-pull-request-change.js
- lib/handle-pull-request-change.js
- lib/is-semantic-message.js
Normally when a GitHub pull request is squashed, the title of the pull request is used in the result squash commit message.
☝️ However! ☝️if that PR contains only one single solitary commit, that commit's message will be used for the squash message, rather than the PR title.
In cases where the PR title is semantic and the single commit is not, this bot was previously giving the green light to merge. This PR changes the behavior, instead setting a pending status and the following message:
> Squashing a PR with only one commit will use that commit’s message. Please push an empty semantic commit. 
Resolves #17
> fix: set pending status on single-commit PRs with a solitary unsemantic commit

- __tests__/handle-pull-request-change.js
- lib/handle-pull-request-change.js
- lib/is-semantic-message.js
Reverts probot/semantic-pull-requests#58
There's a bug. Let's revisit and try again: https://github.com/probot/semantic-pull-requests/pull/58#issuecomment-524688285
h/t @alanhchoi
> Revert "fix: set pending status on single-commit PRs with a solitary unsemantic commit"

- README.md
- __tests__/is-semantic-message.js
- lib/handle-pull-request-change.js
- lib/is-semantic-message.js
Related to #34
By default the type specified in https://github.com/commitizen/conventional-commit-types/blob/01a66a9c4946f51c3018eef4c26cef79ed82205e/index.json will still be used.
Additional types can be specified by adding additional key `types` in `semantic.yml`.
This key should receive an array of type strings.
This will replace the default conventional commit types.
```yml
types:
- feat
- fix
- improvement
- alternative
- other
```
- Added additional params to `isSemanticMessage`
- Added additional tests
- Added additional section for this PR in README
-----
[View rendered README.md](https://github.com/amoshydra/semantic-pull-requests/blob/additional-types/README.md)
> feat: Support additional types

- README.md
- __tests__/handle-pull-request-change.js
- lib/handle-pull-request-change.js
My organization would like to be able to validate PRs using PR title and any (but not every) commit.
This adds an `anyCommit` config option that makes this possible (when used in conjunction with `titleAndCommits: true` or `commitsOnly: true`).
I believe this addresses #41 
-----
[View rendered README.md](https://github.com/ccangialose/semantic-pull-requests/blob/41/add-any-commit-config-option/README.md)
> feat: add config option to validate any commit instead of all commits

- __tests__/handle-pull-request-change.js
- lib/handle-pull-request-change.js
- lib/is-semantic-message.js
This PR changes the app to report a `failure` status instead of `pending` for pull requests that are not yet semantic.
I originally chose to set the `pending` status as a way of keeping the PR from turning  ❌ RED ❌ to avoid causing unnecessary panic:
☝️ However this choice has caused some confusion. When people see the pending status, they tend to think the check is still running/incomplete.
cc @JustinBeckwith @michaelsbradleyjr @gr2m 
Resolves https://github.com/zeke/semantic-pull-requests/issues/76
> fix!: set status to `failure` instead of `pending`

- README.md
- package-lock.json
- package.json
Upgrade `conventional-commit-types` from `2.2.0` to `2.3.0`,
support `improvement`.
> chore: upgrade conventional-commit-types to 2.3.0.

- README.md
- __tests__/handle-pull-request-change.js
- lib/handle-pull-request-change.js
- lib/is-semantic-message.js
Added support for revert commits, because there are cases when our engineers need to rollback a commit without resetting the branch state (revert over reset).
> feat: allow revert commits

- package-lock.json
- package.json
This PR updates Probot to a newer version of the same major version 7 that doesn't make use of the now-deprecated `/installations/:installation_id/access_tokens` endpoint.
> fix: use newer version of probot 7

- __tests__/handle-pull-request-change.js
- __tests__/is-semantic-message.js
- lib/handle-pull-request-change.js
There's a subtle GitHub "bug" where squashed pull requests that only have one commit don't end up creating a squash commit.
This PR will make the GitHub app return a failing check in the following scenario:
- This GitHub app is installed with no custom configuration (no `./github/semantic.yml` file)
- A new pull request is opened with only one commit
- That one commit is not semantic
Resolves https://github.com/zeke/semantic-pull-requests/issues/17
cc @rachmari @jmarlena @lucascosti @martin389
> fix: disallow squashing of unsemantic single-commit PRs

- __tests__/handle-pull-request-change.js
- lib/handle-pull-request-change.js
This fixes yet another caveat of GitHub's behaviour mentioned in #17: GitHub does not count merge commits in this case.
A PR with one regular unsemantic commit and only merge commits afterwards will be allowed by the bot, even though GitHub will replace the squashed title with the one non-merge commit title.
> fix: Fail on single unsemantic non-merge commit

- __tests__/is-semantic-message.js
- lib/is-semantic-message.js
Hey there! Thanks for this cool app.
This PR allows validating multiple scopes, as in accordance with https://github.com/conventional-changelog/commitlint/pull/901.
> feat: Validate multiple scopes

- README.md
- __tests__/handle-pull-request-change.js
- __tests__/is-scope-valid.js
- lib/is-scope-valid.js
- lib/is-semantic-message.js
RegEx support for scopes. This enables support for any project management system to enforce naming conventions in their PRs. 
```
scopes:
- scope1
- /^TASK-(\\d)+$/
...
```
> feat: added regex support for scopes

- .github/workflows/ci.yml
Should prevent future outages like this one: https://github.com/zeke/semantic-pull-requests/issues/125
> fix: run CI on PRs from forks

- README.md
- __tests__/handle-pull-request-change.js
- lib/handle-pull-request-change.js
Our organization allows engineers to create microservices using Spotify's Backstage developer portal. All of these services follow conventional commits. However, we have some repositories in our organization (Helm Charts) that use other release strategies.
We don't want to have to switch to manually adding a newly created service to this configuration every time someone creates a new microservice from Backstage. Instead, we'd rather "opt out" of this merge check on a per-repo basis.
This adds the `enabled` configuration option, which defaults to `true` to avoid breaking changes. This would allow organizations in our situation the ability to set `enabled: false` in `.github/semantic.yml` to disable this merge check.
> feat: add enabled option
